### ISSUE TITLE
CPP Language support with googletest

### ISSUE THREAD

**Issue by amzechochar** [Codium-ai/cover-agent#81]
Although lcov isn't supported yet, I was able to get around it by converting it to cobertura. lcov_cobertura test.info -o  ./coverage.xml cover-agent correctly handles the coverage report, but it is failed in recognizing testing_framework and failed in initial test suite analysis
the content of dotest.sh is :
cd  ~/cover-agent/templated_tests/cppapp
g++ -o test_simple_math_operations test_simple_math_operations.cpp SimpleMathOperations.cpp -lgtest -lgtest_main -pthread -fprofile-arcs -ftest-coverage
./test_simple_math_operations
lcov -c -d . -o test.info --rc lcov_branch_coverage=1
lcov_cobertura test.info -o ./coverage.xml

 poetry run cover-agent \
> --source-file-path "templated_tests/cppapp/SimpleMathOperations.cpp" \
> --test-file-path "templated_tests/cppapp/test_simple_math_operations.cpp" \
> --code-coverage-report-path "templated_tests/cppapp/coverage.xml" \
> --test-command "sh templated_tests/cppapp/dotest.sh" \
> --coverage-type "cobertura" \
> --desired-coverage 50 \
> --max-iterations 4 \
> --model "gpt-4o"
2024-06-02 14:44:54,072 - cover_agent.UnitTestGenerator - INFO - Running build/test command to generate coverage report: "sh templated_tests/cppapp/dotest.sh"
Streaming results from LLM model...
```yaml
language: c++
testing_framework: unknown
number_of_tests: 0
test_headers_indentation: 0
```

Streaming results from LLM model...
```yaml
language: c++
testing_framework: unknown
number_of_tests: 0
relevant_line_number_to_insert_after: 0
```

Streaming results from LLM model...
```yaml
language: c++
testing_framework: unknown
number_of_tests: 0
relevant_line_number_to_insert_after: 0
```

Streaming results from LLM model...
```yaml
language: c++
testing_framework: unknown
number_of_tests: 0
relevant_line_number_to_insert_after: 0
```

2024-06-02 14:45:30,932 - cover_agent.UnitTestGenerator - ERROR - Error during initial test suite analysis: Failed to analyze the relevant line number to insert new tests
Traceback (most recent call last):
  File "/mnt/data/maml2/cover-agent/cover_agent/UnitTestGenerator.py", line 271, in initial_test_suite_analysis
    raise Exception("Failed to analyze the relevant line number to insert new tests")
Exception: Failed to analyze the relevant line number to insert new tests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/maml2/cover-agent/cover_agent/main.py", line 138, in main
    test_gen.initial_test_suite_analysis()
  File "/mnt/data/maml2/cover-agent/cover_agent/UnitTestGenerator.py", line 277, in initial_test_suite_analysis
    raise "Error during initial test suite analysis"
TypeError: exceptions must derive from BaseException
